import streamlit as st
import pandas as pd
import joblib
from io import BytesIO
from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet



import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAXResults


# Load Trained Models

kmeans = joblib.load("kmeans_model.pkl")
scaler = joblib.load("scaler.pkl")
kpca = joblib.load("kpca.pkl")
sarima_model = SARIMAXResults.load("sarima_model.pkl")

page = st.sidebar.radio(
    "Navigation",
    [
        "Cluster Prediction",
        "Electricity Forecast"
    ]
)


# CLUSTER PAGE
if page == "Cluster Prediction":

    st.title("🏠 Household Power Consumption Clustering")

 
    # PDF REPORT FUNCTION

    def create_pdf(
        owner_name,
        household_id,
        data,
        cluster,
        interpretation,
        advice,
    ):
        buffer = BytesIO()

        doc = SimpleDocTemplate(buffer)

        styles = getSampleStyleSheet()

        story = []

        story.append(
            Paragraph(
                "<b>HOUSEHOLD POWER CONSUMPTION CLUSTERING REPORT</b>",
                styles["Title"],
            )
        )

        story.append(Spacer(1, 12))

        story.append(
            Paragraph(
                f"Date Generated: {datetime.now().strftime('%d %B %Y %H:%M')}",
                styles["Normal"],
            )
        )

        story.append(Spacer(1, 12))

        story.append(
            Paragraph(
                f"<b>Owner Name:</b> {owner_name}",
                styles["Normal"],
            )
        )

        story.append(
            Paragraph(
                f"<b>Household ID:</b> {household_id}",
                styles["Normal"],
            )
        )

        story.append(Spacer(1, 15))

        story.append(
            Paragraph(
                "<b>Input Measurements</b>",
                styles["Heading2"],
            )
        )

        table_data = [["Feature", "Value"]]

        for column in data.columns:
            table_data.append(
                [column, str(data.iloc[0][column])]
            )

        table = Table(table_data)

        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                ]
            )
        )

        story.append(table)

        story.append(Spacer(1, 20))

        story.append(
            Paragraph(
                "<b>Prediction Result</b>",
                styles["Heading2"],
            )
        )

        story.append(
            Paragraph(
                f"Predicted Cluster: <b>{cluster}</b>",
                styles["Normal"],
            )
        )

        story.append(
            Paragraph(
                f"Interpretation: {interpretation}",
                styles["Normal"],
            )
        )

        story.append(Spacer(1, 10))

        story.append(
            Paragraph(
                "<b>Recommendation</b>",
                styles["Heading2"],
            )
        )

        story.append(
            Paragraph(
                advice,
                styles["Normal"],
            )
        )

        story.append(Spacer(1, 25))

        story.append(
            Paragraph(
                "Generated by Household Power Consumption Clustering System",
                styles["Italic"],
            )
        )

        doc.build(story)

        buffer.seek(0)

        return buffer


   
    # STREAMLIT PAGE



st.write(
    "Enter the household power consumption measurements below "
    "to predict the household energy consumption cluster."
)


# Household Information

st.subheader("Household Information")

household_id = st.text_input("Household ID")

owner_name = st.text_input("Owner Name")


# Input Features

st.subheader("Power Consumption Measurements")

gap = st.number_input(
    "Global Active Power (kW)",
    min_value=0.0,
    format="%.3f"
)

grp = st.number_input(
    "Global Reactive Power (kW)",
    min_value=0.0,
    format="%.3f"
)

voltage = st.number_input(
    "Voltage (V)",
    min_value=0.0,
    format="%.2f"
)

intensity = st.number_input(
    "Global Intensity (A)",
    min_value=0.0,
    format="%.2f"
)

sm1 = st.number_input(
    "Sub Metering 1 (Wh)",
    min_value=0.0,
    format="%.2f"
)

sm2 = st.number_input(
    "Sub Metering 2 (Wh)",
    min_value=0.0,
    format="%.2f"
)

sm3 = st.number_input(
    "Sub Metering 3 (Wh)",
    min_value=0.0,
    format="%.2f"
)


# DataFrame

training_columns = [
    "Global_active_power",
    "Global_reactive_power",
    "Voltage",
    "Global_intensity",
    "Sub_metering_1",
    "Sub_metering_2",
    "Sub_metering_3"
]

data = pd.DataFrame({
    "Global_active_power": [gap],
    "Global_reactive_power": [grp],
    "Voltage": [voltage],
    "Global_intensity": [intensity],
    "Sub_metering_1": [sm1],
    "Sub_metering_2": [sm2],
    "Sub_metering_3": [sm3]
})



# Ensure the column order exactly matches training
data = data[training_columns]

st.subheader("Input Features")
st.dataframe(data)

# Prediction

if st.button("Predict"):

    # Convert DataFrame to NumPy array
    input_data = data.values

    # Apply preprocessing
    scaled = scaler.transform(input_data)
    reduced = kpca.transform(scaled)

    # Predict cluster
    cluster = int(kmeans.predict(reduced)[0])

    # Cluster names
    cluster_mapping = {
    5: "Very Low",
    2: "Low",
    4: "Low",
    1: "Low-Medium",
    3: "Medium",
    0: "High"
}


    cluster_name = cluster_mapping.get(cluster, "Unknown")

    # Interpretation and advice
    if cluster == 0:
        interpretation = (
            "This household belongs to the High Consumption cluster. "

            "It consumes considerably more electricity than most households. "

            "This may be due to heavy use of electrical appliances, heating/cooling systems, "
            "or inefficient energy usage."
        )

        advice = (
            "• Switch off appliances when not in use.\n"

            "• Replace old appliances with energy-efficient models.\n"

            "• Use LED lighting.\n"

            "• Monitor daily electricity consumption.\n"

            "• Consider installing solar panels if possible."
        )

    elif cluster == 1:
        interpretation = (
            "This household belongs to the Low Consumption cluster. "
            "Electricity usage is generally efficient and within a normal range."
        )

        advice = (
            "• Continue practicing energy-saving habits.\n"
            "• Maintain appliances regularly.\n"
            "• Avoid unnecessary standby power.\n"
            "• Continue monitoring monthly electricity bills."
        )

    elif cluster == 2:
        interpretation = (
            "This household belongs to the Medium Consumption (High Voltage) cluster. "
            "Overall electricity consumption is average, but the household operates under "
            "relatively higher voltage conditions."
        )

        advice = (
            "• Continue efficient electricity usage.\n"
            "• Check voltage stability periodically.\n"
            "• Protect sensitive appliances using surge protectors.\n"
            "• Schedule routine electrical inspections."
        )

    else:
        interpretation = "Unable to determine the household consumption pattern."
        advice = "Please verify the entered values and try again."

    # Display Results
    st.success(f"Predicted Cluster: {cluster}")

    st.subheader("Consumption Regime")
    st.write(f"**{cluster_name}**")

    st.subheader("Interpretation")
    st.info(interpretation)

    st.subheader("Recommendation")
    st.write(advice)

    # Generate PDF
    pdf = create_pdf(
        owner_name,
        household_id,
        data,
        cluster_name,
        interpretation,
        advice
    )

    st.download_button(
        label="📄 Download PDF Report",
        data=pdf,
        file_name=f"{household_id}_Cluster_Report.pdf",
        mime="application/pdf")

elif page == "Electricity Forecast":
    st.title("📈 Household Electricity Consumption Forecast")

st.write(
    """
    Forecast future household electricity consumption
    using the trained SARIMA model.
    """
)

st.subheader("Forecast Settings")

forecast_hours = st.slider(
    "Forecast Horizon (Hours)",
    min_value=24,
    max_value=720,
    value=168,
    step=24
)
if st.button("Generate Forecast"):

    forecast = sarima_model.forecast(steps=forecast_hours)

    forecast_df = pd.DataFrame({
        "Hour": range(1, forecast_hours + 1),
        "Forecasted Global Active Power (kW)": forecast.values
    })

    st.success("Forecast generated successfully!")

    st.subheader("Forecast Table")
    st.dataframe(forecast_df)

    # Forecast plot
    fig, ax = plt.subplots(figsize=(12,5))

    ax.plot(
        forecast_df["Hour"],
        forecast_df["Forecasted Global Active Power (kW)"],
        color="red",
        linewidth=2
    )

    ax.set_title("Future Household Electricity Consumption")

    ax.set_xlabel("Forecast Hour")

    ax.set_ylabel("Global Active Power (kW)")

    ax.grid(True)

    st.pyplot(fig)

    # Forecast statistics
    st.subheader("Forecast Summary")

    st.metric(
        "Average Forecast",
        f"{forecast_df['Forecasted Global Active Power (kW)'].mean():.2f} kW"
    )

    st.metric(
        "Maximum Forecast",
        f"{forecast_df['Forecasted Global Active Power (kW)'].max():.2f} kW"
    )

    st.metric(
        "Minimum Forecast",
        f"{forecast_df['Forecasted Global Active Power (kW)'].min():.2f} kW"
    )

    # download the csv
    csv = forecast_df.to_csv(index=False)

    st.download_button(
        "⬇ Download Forecast CSV",
        csv,
        file_name="Electricity_Forecast.csv",
        mime="text/csv"
    )